# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_getting_started',
                'doc_host': 'https://jeromeku.github.io',
                'git_url': 'https://github.com/jeromeku/nbdev_getting_started',
                'lib_path': 'nbdev_getting_started'},
  'syms': {'nbdev_getting_started.core': {'nbdev_getting_started.core.foo': ('core.html#foo', 'nbdev_getting_started/core.py')}}}
